

class Currency{
  static Map<String, String> CurrencyWithCode = {
    "AFN":"Afghani",
    "DZD":"Algerian Dinar",
    "ARS":"Argentine Peso",
    "AMD":"Armenian Dram",
    "AWG":"Aruban Florin",
    "AUD":"Australian Dollar",
    "AZN":"Azerbaijanian Manat",
    "BSD":"Bahamian Dollar",
    "BHD":"Bahraini Dinar",
    "THB":"Baht",
    "PAB":"Balboa",
    "BBD":"Barbados Dollar",
    "BYN":"Belarussian Ruble",
    "BZD":"Belize Dollar",
    "BMD":"Bermudian Dollar",
    "BOB":"Boliviano",
    "BRL":"Brazilian Real",
    "BND":"Brunei Dollar",
    "BGN":"Bulgarian Lev",
    "BIF":"Burundi Franc",
    "CVE":"Cabo Verde Escudo",
    "CAD":"Canadian Dollar",
    "KYD":"Cayman Islands Dollar",
    "XOF":"CFA Franc BCEAO",
    "XAF":"CFA Franc BEAC",
    "XPF":"CFP Franc",
    "CLP":"Chilean Peso",
    "COP":"Colombian Peso",
    "KMF":"Comoro Franc",
    "CDF":"Congolese Franc",
    "BAM":"Convertible Mark",
    "NIO":"Cordoba Oro",
    "CRC":"Costa Rican Colon",
    "CUP":"Cuban Peso",
    "CZK":"Czech Koruna",
    "GMD":"Dalasi",
    "DKK":"Danish Krone",
    "MKD":"Denar",
    "DJF":"Djibouti Franc",
    "STN":"Dobra",
    "DOP":"Dominican Peso",
    "VND":"Dong",
    "XCD":"East Caribbean Dollar",
    "EGP":"Egyptian Pound",
    "SVC":"El Salvador Colon",
    "ETB":"Ethiopian Birr",
    "EUR":"Euro",
    "FKP":"Falkland Islands Pound",
    "FJD":"Fiji Dollar",
    "HUF":"Forint",
    "GHS":"Ghana Cedi",
    "GIP":"Gibraltar Pound",
    "HTG":"Gourde",
    "PYG":"Guarani",
    "GNF":"Guinea Franc",
    "GYD":"Guyana Dollar",
    "HKD":"Hong Kong Dollar",
    "UAH":"Hryvnia",
    "ISK":"Iceland Krona",
    "INR":"Indian Rupee",
    "IRR":"Iranian Rial",
    "IQD":"Iraqi Dinar",
    "JMD":"Jamaican Dollar",
    "JOD":"Jordanian Dinar",
    "KES":"Kenyan Shilling",
    "PGK":"Kina",
    "LAK":"Kip",
    "KWD":"Kuwaiti Dinar",
    "MWK":"Kwacha",
    "AOA":"Kwanza",
    "MMK":"Kyat",
    "GEL":"Lari",
    "LBP":"Lebanese Pound",
    "ALL":"Lek",
    "HNL":"Lempira",
    "SLE":"Leone",
    "LRD":"Liberian Dollar",
    "LYD":"Libyan Dinar",
    "SZL":"Lilangeni",
    "LSL":"Loti",
    "MGA":"Malagasy Ariary",
    "MYR":"Malaysian Ringgit",
    "MUR":"Mauritius Rupee",
    "MXN":"Mexican Peso",
    "MDL":"Moldovan Leu",
    "MAD":"Moroccan Dirham",
    "MZN":"Mozambique Metical",
    "NGN":"Naira",
    "ERN":"Nakfa",
    "NAD":"Namibia Dollar",
    "NPR":"Nepalese Rupee",
    "ILS":"New Israeli Sheqel",
    "TWD":"New Taiwan Dollar",
    "NZD":"New Zealand Dollar",
    "BTN":"Ngultrum",
    "KPW":"North Korean Won",
    "NOK":"Norwegian Krone",
    "PEN":"Nuevo Sol",
    "MRU":"Ouguiya",
    "PKR":"Pakistan Rupee",
    "MOP":"Pataca",
    "TOP":"Pa’anga",
    "UYU":"Peso Uruguayo",
    "PHP":"Philippine Peso",
    "GBP":"Pound Sterling",
    "BWP":"Pula",
    "QAR":"Qatari Rial",
    "GTQ":"Quetzal",
    "ZAR":"Rand",
    "OMR":"Rial Omani",
    "KHR":"Riel",
    "RON":"Romanian Leu",
    "MVR":"Rufiyaa",
    "IDR":"Rupiah",
    "RUB":"Russian Ruble",
    "RWF":"Rwanda Franc",
    "SHP":"Saint Helena Pound",
    "SAR":"Saudi Riyal",
    "XDR":"SDR (Special Drawing Right)",
    "RSD":"Serbian Dinar",
    "SCR":"Seychelles Rupee",
    "SGD":"Singapore Dollar",
    "SBD":"Solomon Islands Dollar",
    "KGS":"Som",
    "SOS":"Somali Shilling",
    "TJS":"Somoni",
    "SSP":"South Sudanese Pound",
    "LKR":"Sri Lanka Rupee",
    "SDG":"Sudanese Pound",
    "SRD":"Surinam Dollar",
    "SEK":"Swedish Krona",
    "CHF":"Swiss Franc",
    "SYP":"Syrian Pound",
    "BDT":"Taka",
    "WST":"Tala",
    "TZS":"Tanzanian Shilling",
    "KZT":"Tenge",
    "TTD":"Trinidad and Tobago Dollar",
    "MNT":"Tugrik",
    "TND":"Tunisian Dinar",
    "TRY":"Turkish Lira",
    "TMT":"Turkmenistan New Manat",
    "AED":"UAE Dirham",
    "UGX":"Uganda Shilling",
    "CLF":"Unidad de Fomento",
    "COU":"Unidad de Valor Real",
    "UYI":"Uruguay Peso en Unidades Indexadas (URUIURUI)",
    "USD":"US Dollar",
    "UZS":"Uzbekistan Sum",
    "VUV":"Vatu",
    "KRW":"Won",
    "YER":"Yemeni Rial",
    "JPY":"Yen",
    "CNY":"Yuan Renminbi",
    "ZMW":"Zambian Kwacha",
    "ZWL":"Zimbabwe Dollar",
    "PLN":"Zloty",

  };

}